In [22]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
from math import sqrt
from scipy import stats
from sklearn.decomposition import PCA
import scipy.linalg as la
from scipy.spatial import distance


In [23]:
B = np.array([[2, 2, 1, 2], [1, 3, 0, 3], [0, 1, 3, 1], [3, 2, 3, 0], [1, 3, 1, 3], [1, 0, 1, 2]])

In [24]:
row_means = np.mean(B, axis=1)

In [25]:
# subtract the row means
B = B.astype(np.float)
for i in range(B.shape[1]): 
    B[:,i] -= row_means  

In [26]:
B

array([[ 0.25,  0.25, -0.75,  0.25],
       [-0.75,  1.25, -1.75,  1.25],
       [-1.25, -0.25,  1.75, -0.25],
       [ 1.  ,  0.  ,  1.  , -2.  ],
       [-1.  ,  1.  , -1.  ,  1.  ],
       [ 0.  , -1.  ,  0.  ,  1.  ]])

In [27]:
A = B
A_transpose = np.transpose(A)
C = (np.matmul(A, A_transpose))

In [28]:
D, U, V = la.svd(A, full_matrices=True, compute_uv=True)
print(D)
print(U)

[[ 0.16408622  0.2443382  -0.07100155  0.64819859  0.61365756 -0.33406036]
 [ 0.62780739  0.1070203   0.29337893  0.4386627  -0.49702136  0.26244646]
 [-0.26039808 -0.80167357  0.39519489  0.36228709  0.03887874 -0.0238713 ]
 [-0.53891957  0.42774159  0.34390332  0.21089066  0.11334117  0.59246286]
 [ 0.46372117 -0.1373179   0.36438048 -0.40891558  0.59092315  0.34195205]
 [ 0.0751984  -0.29042369 -0.70828381  0.21089066  0.11334117  0.59246286]]
[4.04144436e+00 2.22387915e+00 1.72368473e+00 3.92365926e-16]


In [29]:
u1 = [ 0.1641,  0.6278 , -0.2604,  -0.5389,  0.4637,
         0.0752]

In [30]:
u2 = [ 0.2443,  0.1070 ,  -0.8017,  0.4277 , -0.1373,
          -0.2904]

In [31]:
u3 = [-0.0710 , 0.2934, 0.3952,  0.3439,  0.3644,
         -0.7083]

In [32]:
X1 = A[:,0]
X1 = X1.reshape((6, 1))
X2 = A[:, 1]
X2 = X2.reshape((6, 1))
X3 = A[:,2]
X3 = X3.reshape((6, 1))
X4 = A[:, 3]
X4 = X4.reshape((6, 1))

In [33]:
score = np.array([-1.1069,1.5480])

In [34]:
print(np.dot(u1, X1))
print(np.dot(u2, X1))
#print(np.dot(u3, X1))

print(np.dot(u1, X2))
print(np.dot(u2, X2))
#print(np.dot(u3, X2))

print(np.dot(u1, X3))
print(np.dot(u2, X3))
#print(np.dot(u3, X3))

print(np.dot(u1, X4))
print(np.dot(u2, X4))
#print(np.dot(u3, X4))

score_matrix = np.array([-1.106925, 1.279375, -2.680025, 2.507575, 1.54795, 0.54835, -1.20845,-0.88785])
score_matrix = score_matrix.reshape((2, 4))

[-1.106925]
[1.54795]
[1.279375]
[0.54835]
[-2.680025]
[-1.20845]
[2.507575]
[-0.88785]


In [35]:
Y = np.array([[2, 1, 0, 3, 1, 1]])
Y = Y.reshape((6, 1))

In [36]:
Y = Y.astype(np.float)
for i in range(Y.shape[1]): 
    Y[:,i] -= row_means  
print(Y)

[[ 0.25]
 [-0.75]
 [-1.25]
 [ 1.  ]
 [-1.  ]
 [ 0.  ]]


In [37]:
print(np.dot(u1, Y))
print(np.dot(u2, Y))
W = np.array([[-1.106925], [1.54795]])

[-1.106925]
[1.54795]


In [38]:
sum_sq = np.sum(np.square(W - score)) 
sum_sq

14.096855281249999

In [39]:
score = W

In [40]:
dst = distance.euclidean(score, W)
dst

0.0

In [41]:
pca = decomposition.PCA(n_components=2)
X = pca.fit_transform(X)

NameError: name 'decomposition' is not defined

In [49]:
lambdas = np.array([[4.04144436, 1.2364, 0.7428]])

In [53]:
print(np.sqrt(lambdas[:,0]) * u1)
print(np.sqrt(lambdas[:,1]) * u2)
print(np.sqrt(lambdas[:,2]) * u3)

[ 0.32989587  1.26208793 -0.52349108 -1.0833692   0.93219206  0.15117715]
[ 0.27164578  0.11897707 -0.89143849  0.47557471 -0.15266871 -0.322906  ]
[-0.06119195  0.25286927  0.34060646  0.29639312  0.31406122 -0.61045435]
