In [24]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
from math import sqrt
from scipy import stats
from sklearn.decomposition import PCA
import scipy.linalg as la
from scipy.spatial import distance

In [25]:
# define the matrix:
B = np.array([[2, -2, -1, 3], [-1, 3, 3, -1], [0, 2, 3, 0], [1, 3, 1, 3], [1, 0, -1, 2], [-3, 2, 4, -1], [5, -1, 5, 3], [2, 1, 2, 0]])

In [26]:
# compute the row means
row_means = np.mean(B, axis=1)

In [27]:
# subtract the row means
B = B.astype(np.float)
for i in range(B.shape[1]): 
    B[:,i] -= row_means  

In [28]:
# subtract the row means
B = B.astype(np.float)
for i in range(B.shape[1]): 
    B[:,i] -= row_means  

In [29]:
# compute the eigenvalues/eigenvectors (use svd)
la.svd(C, full_matrices=True, compute_uv=True)

(array([[-0.06034213,  0.4781237 , -0.11987829,  0.4527863 ,  0.23811444,
         -0.64018626,  0.16768254,  0.231767  ],
        [-0.2634675 , -0.43843494, -0.11699986, -0.21492963,  0.54869919,
         -0.19326684,  0.51447287, -0.27453738],
        [-0.31948918, -0.24997171, -0.05615329, -0.05563285, -0.68553908,
         -0.19542125,  0.43732551,  0.36025783],
        [-0.32742499,  0.02341772, -0.82488343, -0.02112292,  0.12420066,
          0.26708138, -0.23636054,  0.26218516],
        [-0.03197875,  0.23092633, -0.35394178,  0.09690335, -0.38621429,
         -0.10140833,  0.08593642, -0.80259277],
        [-0.22921935, -0.5692679 ,  0.08809548,  0.66216031, -0.02803782,
         -0.10914919, -0.3849925 , -0.12750121],
        [-0.75831666,  0.37248165,  0.38478856,  0.07929323,  0.06871488,
          0.33990509,  0.05454717, -0.09290318],
        [-0.29842073, -0.00167046,  0.08518522, -0.53955044, -0.04660196,
         -0.55277019, -0.54909074, -0.05782576]]),
 array([8.2778

In [30]:
A = B
A_transpose = np.transpose(A)
C = (np.matmul(A, A_transpose))

In [31]:
# principal components
u1 = (np.array([[-0.46536222,   0.46992727,  0.29148827,  0.01799517, -0.22596605,
          0.59653918, -0.26182389,  0.04296201]]))
u2 = (np.array([[-0.03737162, -0.04179176, -0.1539934 ,  0.35316746,  0.19747961,
         -0.21056644, -0.84376578, -0.23051788 ]]))
u3 = (np.array([[0.48276203, -0.10894711,  0.03582972,  0.33194317,  0.22044514,
          0.61144594,  0.13821706, -0.44948322]]))

In [32]:
D, U, V = la.svd(A, full_matrices=True, compute_uv=True)
print(D)
print(U)

[[ 0.06034213  0.4781237   0.11987829 -0.4527863  -0.31194574  0.43273032
  -0.50714515  0.0812923 ]
 [ 0.2634675  -0.43843494  0.11699986  0.21492963  0.07805462 -0.09601525
  -0.73303134 -0.35472464]
 [ 0.31948918 -0.24997171  0.05615329  0.05563285 -0.17178555  0.68452209
   0.38751082 -0.42537889]
 [ 0.32742499  0.02341772  0.82488343  0.02112292 -0.2699391  -0.29056477
   0.17905358  0.14835916]
 [ 0.03197875  0.23092633  0.35394178 -0.09690335  0.87251367  0.20231452
   0.0127667  -0.09279596]
 [ 0.22921935 -0.5692679  -0.08809548 -0.66216031  0.14461832  0.00475925
   0.0390987   0.39333146]
 [ 0.75831666  0.37248165 -0.38478856 -0.07929323  0.07443338 -0.30746056
   0.08826955 -0.15491855]
 [ 0.29842073 -0.00167046 -0.08518522  0.53955044  0.0805298   0.33917746
  -0.1173065   0.69085734]]
[9.09827294 8.47029161 4.0360218  2.27730489]


In [33]:
X1 = A[:,0]
X1 = X1.reshape((8, 1))
X2 = A[:, 1]
X2 = X2.reshape((8, 1))
X3 = A[:,2]
X3 = X3.reshape((8, 1))
X4 = A[:, 3]
X4 = X4.reshape((8, 1))

u1

In [34]:
print(np.dot(u1, X1))
print(np.dot(u2, X1))
print(np.dot(u3, X1))

print(np.dot(u1, X2))
print(np.dot(u2, X2))
print(np.dot(u3, X2))

print(np.dot(u1, X3))
print(np.dot(u2, X3))
print(np.dot(u3, X3))

print(np.dot(u1, X4))
print(np.dot(u2, X4))
print(np.dot(u3, X4))



[[-4.80366405]]
[[1.21477526]]
[[-2.63505966]]
[[4.29310407]]
[[5.63824357]]
[[-1.80938502]]
[[3.97430286]]
[[-1.17118142]]
[[-0.57241373]]
[[-3.82819986]]
[[3.80865261]]
[[0.57745805]]


In [37]:

score_matrix = np.array([[-4.71254981,
-1.15784725,
-1.52520957,
4.38421832,
3.26562107,
-0.69953493,
4.0654171,
-3.54380392,
0.53743636,
-3.73708561,
1.4360301,
1.68730814]])
score_matrix.reshape(3,4)

array([[-4.71254981, -1.15784725, -1.52520957,  4.38421832],
       [ 3.26562107, -0.69953493,  4.0654171 , -3.54380392],
       [ 0.53743636, -3.73708561,  1.4360301 ,  1.68730814]])

In [36]:
# part B: initialize the vectors
Y1 = (np.array([[1, 5, 1, 5, 5, 1, 1, 3]]))
Y2 = (np.array([[-2, 3, 2, 3, 0, 2, -1, 1]]))
Y3 = (np.array([[2, -3, 2, 3, 0, 0, 2, -1]]))
Y4 = (np.array([[2, -2, 2, 2, -1, 1, 2, 2]]))

In [200]:
# create a matrix with all y-vectors
Y = np.array([[1, 5, 1, 5, 5, 1, 1, 3], [-2, 3, 2, 3, 0, 2, -1, 1], [2, -3, 2, 3, 0, 0, 2, -1], [2, -2, 2, 2, -1, 1, 2, 2]])
Y.reshape(8,4)

array([[ 1,  5,  1,  5],
       [ 5,  1,  1,  3],
       [-2,  3,  2,  3],
       [ 0,  2, -1,  1],
       [ 2, -3,  2,  3],
       [ 0,  0,  2, -1],
       [ 2, -2,  2,  2],
       [-1,  1,  2,  2]])

In [201]:
# subtract the mean for each y-vector
Y = Y.astype(np.float)
Y = np.transpose(Y)
for i in range(Y.shape[1]): 
    Y[:,i] -= row_means 

In [203]:
a = (np.dot(u1, Y[:,0]))
b = (np.dot(u2, Y[:,0]))
c = (np.dot(u3, Y[:,0]))
d = (np.dot(u1, Y[:,1]))
e = (np.dot(u2, Y[:,1]))
f = (np.dot(u3, Y[:,1]))
g = (np.dot(u1, Y[:,2]))
h = (np.dot(u2, Y[:,2]))
i = (np.dot(u3, Y[:,2]))
j = (np.dot(u1, Y[:,3]))
k = (np.dot(u2, Y[:,3]))
l = (np.dot(u3, Y[:,3]))

dist1 = np.sqrt(np.linalg.norm(a - score_matrix[0]))
dist2 = np.linalg.norm(np.dot(Y1, u2) - score_matrix[1])
dist3 = np.linalg.norm(np.dot(Y1, u3) - score_matrix[2])

print(dist1)
print(dist2)
print(dist3)


In [209]:
sum_sq = np.sum(np.square(a - score_matrix[:,0])) 
sum_sq

38.70015526220766

In [210]:
sum_sq = np.sum(np.square(b - score_matrix[:,0])) 
sum_sq

59.16990984043806

In [211]:
sum_sq = np.sum(np.square(c - score_matrix[:,0])) 
sum_sq

32.94428018243086

In [212]:
sum_sq = np.sum(np.square(d - score_matrix[:,1])) 
sum_sq

30.714490726758765

In [213]:
sum_sq = np.sum(np.square(e - score_matrix[:,1])) 
sum_sq

19.567071933808947

In [214]:
sum_sq = np.sum(np.square(f - score_matrix[:,1])) 
sum_sq

0.2100501826637825

In [215]:
sum_sq = np.sum(np.square(g - score_matrix[:,2])) 
sum_sq

0.6989940913215821

In [216]:
sum_sq = np.sum(np.square(h - score_matrix[:,2])) 
sum_sq

10.516828574444979

In [217]:
sum_sq = np.sum(np.square(i - score_matrix[:,2])) 
sum_sq

12.257919399522946

In [218]:
sum_sq = np.sum(np.square(j - score_matrix[:,3])) 
sum_sq

28.538707602012604

In [219]:
sum_sq = np.sum(np.square(k - score_matrix[:,3])) 
sum_sq

17.314093973202016

In [220]:
sum_sq = np.sum(np.square(l - score_matrix[:,3])) 
sum_sq

14.490476646770654